#!/bin/bash
if [[ $(lsusb | grep "046d:0a44") ]]; then
    pactl set-default-sink alsa_output.usb-Logitech_Logitech_USB_Headset-00.analog-stereo
    pactl set-sink-mute alsa_output.usb-Logitech_Logitech_USB_Headset-00.analog-stereo toggle
else
    pactl set-default-sink alsa_output.pci-0000_00_1b.0.analog-stereo
    pactl set-sink-mute  alsa_output.pci-0000_00_1b.0.analog-stereo toggle
fi    
